include: package:lints/recommended.yaml

linter:
  rules:
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    one_member_abstracts: true
    prefer_final_in_for_each: true
    package_api_docs: true
    public_member_api_docs: false
    comment_references: true
    lines_longer_than_80_chars: true
    prefer_interpolation_to_compose_strings: false
    always_use_package_imports: true
